### ISSUE TITLE
when i submit a sample,get this error:start() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by tongsens** [idanr1986/cuckoo-droid#13]
how can i slove this problem? 

2016-08-29 03:43:25,712 [modules.machinery.avd] INFO: Stopping AVD listening on port 5554
2016-08-29 03:43:26,734 [lib.cuckoo.core.scheduler] ERROR: Failure in AnalysisManager.run
Traceback (most recent call last):
  File "/root/cuckoo/lib/cuckoo/core/scheduler.py", line 519, in run
    self.launch_analysis()
  File "/root/cuckoo/lib/cuckoo/core/scheduler.py", line 385, in launch_analysis
    machinery.start(self.machine.label, self.task)
TypeError: start() takes exactly 2 arguments (3 given)

**Comment by idanr1986** [comment]
did you used the script for merging cuckoo 1.2 with cuckoodroid?

**Comment by tongsens** [comment]
i del all, than re-download the git code, than i can run it normal

**Comment by lovina37** [comment]
@tongsens did u solve this I have same error

**Comment by wickywaka** [comment]
For me this error was appearing when I tried to use cuckoo 2.0-rc2. With cuckoo 1.2 this error is no more appearing. But now I am stuck at `INFO: Task #2: acquired machine aosx_1`. I am using avd on host machine.
