### ISSUE TITLE
Throwing error while running ./cuckoo

### ISSUE THREAD

**Issue by zimmyseth** [idanr1986/cuckoo-droid#17]
Hi,

I have followed steps mentioned on http://cuckoo-droid.readthedocs.io/en/latest/installation/guest_android_avd/

While running "./cuckoo.py" I am getting following errors. Help will be appreciable.

Traceback (most recent call last):
  File "./cuckoo.py", line 100, in <module>
    cuckoo_init(quiet=args.quiet, debug=args.debug, artwork=args.artwork,test=args.test)
  File "./cuckoo.py", line 59, in cuckoo_init
    init_modules()
  File "/home/root1/cuckoo/lib/cuckoo/core/startup.py", line 198, in init_modules
    import_package(modules.processing)
  File "/home/root1/cuckoo/lib/cuckoo/core/plugins.py", line 43, in import_package
    import_plugin(name)
  File "/home/root1/cuckoo/lib/cuckoo/core/plugins.py", line 30, in import_plugin
    module = __import__(name, globals(), locals(), ["dummy"], -1)
  File "/home/root1/cuckoo/modules/processing/apkinfo.py", line 11, in <module>
    from lib.cuckoo.api.androguard_extentions import get_show_NativeMethods, get_show_CryptoCode, get_show_Permissions, \
  File "/home/root1/cuckoo/lib/cuckoo/api/androguard_extentions.py", line 1, in <module>
    from androguard.core.analysis.analysis import PathVar, TAINTED_PACKAGE_CALL
  File "/usr/local/lib/python2.7/dist-packages/androguard/core/analysis/analysis.py", line 20, in <module>
    from androguard.core.analysis.sign import Signature, TAINTED_PACKAGE_CREATE, \
  File "/usr/local/lib/python2.7/dist-packages/androguard/core/analysis/sign.py", line 19, in <module>
    from androguard.core.bytecodes import dvm
  File "/usr/local/lib/python2.7/dist-packages/androguard/core/bytecodes/dvm.py", line 2402
    print(nb, end=' ')
                 ^
SyntaxError: invalid syntax

**Comment by idanr1986** [comment]
really weird error try executing python2.7 "python cuckoo.py"
