### ISSUE TITLE
Droidmon FATAL EXCEPTION

### ISSUE THREAD

**Issue by berii** [idanr1986/cuckoo-droid#2]
Hi,
The hooking of setRequestProperty causes the application to crash (see log below). 
Is it possible to share the source code so I can fix the few errors I am getting.

Thanks
---- FATAL EXC
1238-1566/? E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #3
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:299)
            at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.IllegalStateException: Cannot set request property after connection is made
            at libcore.net.http.HttpURLConnectionImpl.setRequestProperty(HttpURLConnectionImpl.java:491)
            at com.google.ads.util.AdUtil.a(Unknown Source)
            at b.a(Unknown Source)
            at b.doInBackground(Unknown Source)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)

**Comment by idanr1986** [comment]
yes i working on the new version and the source code will be available soon

**Comment by cuckoooo** [comment]
droimon not working in cuckoodroid due to error (droidmon error:/data/local/tmp/hooks.json:open failed:ENOENT(No such file or directory)

**Comment by idanr1986** [comment]
https://github.com/idanr1986/droidmon
