### ISSUE TITLE
i use second method ,but the  dynamic analy in emulator can't work

### ISSUE THREAD

**Issue by shiyelin** [idanr1986/cuckoo-droid#20]
2016-12-06 12:50:48,873 [lib.cuckoo.core.guest] DEBUG: aosx_1: status ready
2016-12-06 12:50:48,890 [lib.cuckoo.core.guest] DEBUG: Uploading analyzer to guest (id=aosx_1, ip=127.0.0.1)
2016-12-06 12:51:13,105 [lib.cuckoo.core.scheduler] ERROR: aosx_1: guest communication timeout, check networking or try to increase timeout
2016-12-06 12:51:13,215 [modules.machinery.avd] DEBUG: Stopping vm aosx_1
2016-12-06 12:51:13,216 [modules.machinery.avd] INFO: Stopping AVD listening on port 5554

ip is right  
2016-12-06 11:46:34,501 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "network_http":
Traceback (most recent call last):
  File "/home/cuckoodroid/cuckoo/lib/cuckoo/core/plugins.py", line 342, in process
    if current.run():
  File "/home/cuckoodroid/cuckoo/modules/signatures/network_http.py", line 27, in run
    if "http" in self.results["network"]:
KeyError: 'network'
2016-12-06 11:46:34,545 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "network_icmp":
Traceback (most recent call last):
  File "/home/cuckoodroid/cuckoo/lib/cuckoo/core/plugins.py", line 342, in process
    if current.run():
  File "/home/cuckoodroid/cuckoo/modules/signatures/network_icmp.py", line 27, in run
    if "icmp" in self.results["network"]:
KeyError: 'network'
2016-12-06 11:46:34,547 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "network_irc":
Traceback (most recent call last):
  File "/home/cuckoodroid/cuckoo/lib/cuckoo/core/plugins.py", line 342, in process
    if current.run():
  File "/home/cuckoodroid/cuckoo/modules/signatures/network_irc.py", line 27, in run
    if "irc" in self.results["network"]:
KeyError: 'network'
2016-12-06 11:46:34,548 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "network_smtp":
Traceback (most recent call last):
  File "/home/cuckoodroid/cuckoo/lib/cuckoo/core/plugins.py", line 342, in process
    if current.run():
  File "/home/cuckoodroid/cuckoo/modules/signatures/network_smtp.py", line 27, in run
    if "smtp" in self.results["network"]:
KeyError: 'network'

**Comment by shiyelin** [comment]
the agent.py need run in android emulator？
